// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\gamin\OneDrive\Desktop\sosmed-app\sosmed-golang\internal\repositories\feed_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/davidafdal/post-app/internal/entities"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFeedRepository is a mock of FeedRepository interface.
type MockFeedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedRepositoryMockRecorder
}

// MockFeedRepositoryMockRecorder is the mock recorder for MockFeedRepository.
type MockFeedRepositoryMockRecorder struct {
	mock *MockFeedRepository
}

// NewMockFeedRepository creates a new mock instance.
func NewMockFeedRepository(ctrl *gomock.Controller) *MockFeedRepository {
	mock := &MockFeedRepository{ctrl: ctrl}
	mock.recorder = &MockFeedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedRepository) EXPECT() *MockFeedRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeedRepository) Create(ctx context.Context, feed *entities.Feed) (*entities.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, feed)
	ret0, _ := ret[0].(*entities.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFeedRepositoryMockRecorder) Create(ctx, feed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedRepository)(nil).Create), ctx, feed)
}

// GetFeeds mocks base method.
func (m *MockFeedRepository) GetFeeds(ctx context.Context, userID uuid.UUID, limit int) ([]*entities.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeeds", ctx, userID, limit)
	ret0, _ := ret[0].([]*entities.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeeds indicates an expected call of GetFeeds.
func (mr *MockFeedRepositoryMockRecorder) GetFeeds(ctx, userID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeeds", reflect.TypeOf((*MockFeedRepository)(nil).GetFeeds), ctx, userID, limit)
}

// ToggleLiked mocks base method.
func (m *MockFeedRepository) ToggleLiked(feedID, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLiked", feedID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleLiked indicates an expected call of ToggleLiked.
func (mr *MockFeedRepositoryMockRecorder) ToggleLiked(feedID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLiked", reflect.TypeOf((*MockFeedRepository)(nil).ToggleLiked), feedID, userID)
}
