// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\gamin\OneDrive\Desktop\sosmed-app\sosmed-golang\pkg\upload\upload.go

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUploadUseCase is a mock of UploadUseCase interface.
type MockUploadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUploadUseCaseMockRecorder
}

// MockUploadUseCaseMockRecorder is the mock recorder for MockUploadUseCase.
type MockUploadUseCaseMockRecorder struct {
	mock *MockUploadUseCase
}

// NewMockUploadUseCase creates a new mock instance.
func NewMockUploadUseCase(ctrl *gomock.Controller) *MockUploadUseCase {
	mock := &MockUploadUseCase{ctrl: ctrl}
	mock.recorder = &MockUploadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadUseCase) EXPECT() *MockUploadUseCaseMockRecorder {
	return m.recorder
}

// SaveTempFile mocks base method.
func (m *MockUploadUseCase) SaveTempFile(fileHeader *multipart.FileHeader, tempDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTempFile", fileHeader, tempDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTempFile indicates an expected call of SaveTempFile.
func (mr *MockUploadUseCaseMockRecorder) SaveTempFile(fileHeader, tempDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTempFile", reflect.TypeOf((*MockUploadUseCase)(nil).SaveTempFile), fileHeader, tempDir)
}
